#     ___           __             _____                               _____          ____
#    / _ \___  ____/ /_____ ____  / ___/__  __ _  ___  ___  ___ ___   / ___/__  ___  / _(_)__ _
#   / // / _ \/ __/  '_/ -_) __/ / /__/ _ \/  ' \/ _ \/ _ \(_-</ -_) / /__/ _ \/ _ \/ _/ / _ `/
#  /____/\___/\__/_/\_\\__/_/    \___/\___/_/_/_/ .__/\___/___/\__/  \___/\___/_//_/_//_/\_, /
#                                              /_/                                      /___/
version: "3.1"
services:

  web:
    build:
      context: .
    image: herokuphp
    command: 'bash -c "source .env && tools/start-web.sh"'
    working_dir: /app/user
    ports:
      - 8080:8080
    volumes:
      - .:/app/user:rw,cached
    links:
      - mysql
      - redis
    environment:
      - VIRTUAL_HOST=spimarexpo.test

  shell:
    build:
      context: .
    image: herokuphp
    command: 'bash -c "source .env && bash"'
    working_dir: /app/user
    volumes:
      - .:/app/user:rw,cached
    links:
      - mysql
      - redis

  adminer:
    image: clue/adminer:latest
    ports:
      - 8081:80
    links:
      - mysql

  mysql:
    image: mysql:latest
    volumes:
        - ./docker/db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spimarexpo
      MYSQL_USER: h4x0r
      MYSQL_PASSWORD: root
    restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379